### ISSUE TITLE
建议增加知名度

### ISSUE THREAD

**Issue by Saltro** [wzkMaster/awesome-SIM#1]
建议改一个项目名，再加一个方便搜到的description
顺便建议将范围收拢到WHU SIM👀不同学校SIM差别太大

**Comment by wzkMaster** [comment]
可以哈哈👀
现在还没有完全成型，等毕业论文搞完再找人补充一些其他内容和完善项目细节，之后再来增加知名度。

欢迎一起来搞，可以写一篇转码指南😆

**Comment by wzkMaster** [comment]
> 建议改一个项目名，再加一个方便搜到的description 顺便建议将范围收拢到WHU SIM👀不同学校SIM差别太大

可以哈哈👀
现在还没有完全成型，等毕业论文搞完再找人补充一些其他内容和完善项目细节，之后再来增加知名度。

欢迎一起来搞，可以写一篇转码指南😆

**Comment by little-weakduck** [comment]
让啥都不懂得装个node.js和pnpm我觉得有点为难他们了😂

**Comment by little-weakduck** [comment]
> 让啥都不懂得装个node.js和pnpm我觉得有点为难他们了😂

我觉得可以考虑部署上GitHub Pages

**Comment by wzkMaster** [comment]
> > 让啥都不懂得装个node.js和pnpm我觉得有点为难他们了😂
> 
> 我觉得可以考虑部署上GitHub Pages

我目前有部署在vercel上面（项目页右边有[链接](https://awesome-sim.vercel.app/)），不过vercel似乎会被墙，后续再看看要换成github pages还是弄个国内可以访问的域名。那个命令的部分主要是给想本地跑项目的同学用。
